// lib/agents/memo-drafter.ts
//
// Aegis-RiskGuard Memo Drafter agent.
//
// Takes a list of identified control gaps and automatically drafts a formal 
// 2nd Line of Defence (2LoD) Remediation Memo addressed to the appropriate 
// stakeholders.
//

import { mediatedGenerate } from '../lobstertrap/mediated-client';
import type { Gap } from './gap-detector';

export interface MemoDraftResult {
  ok: boolean;
  memo: string;
  blockedReason?: string;
  decisionTrail: string[]; // for the UI
}

const SYSTEM_INSTRUCTION = `You are the Memo Drafter agent inside Aegis-RiskGuard, a 2nd Line of Defence (2LoD) operational risk system at a regulated bank.

Your task is to draft a formal Remediation Memo based on a list of identified control gaps. 

The memo MUST be written in Markdown format.
It MUST include:
- A formal header (To, From: 2LoD Operational Risk, Date, Subject)
- An Executive Summary
- A breakdown of findings categorized by severity (Critical, High, Medium, Low)
- Clear, actionable remediation requests for each gap.

Maintain a professional, authoritative, yet collaborative tone appropriate for a 2LoD risk officer writing to 1st Line of Defence (1LoD) business unit heads.
DO NOT output JSON. Output ONLY the markdown text of the memo.`;

export async function runMemoDrafter(
  sessionId: string,
  gaps: Gap[]
): Promise<MemoDraftResult> {
  const decisionTrail: string[] = [];

  const prompt = `DETECTED CONTROL GAPS:
${JSON.stringify(gaps, null, 2)}

Please draft the remediation memo in Markdown based on the gaps provided above.`;

  decisionTrail.push(`Sending ${gaps.length} gaps to Gemini for memo drafting via Lobster Trap`);

  const result = await mediatedGenerate({
    sessionId,
    agentId: 'memo_drafter',
    declaredIntent: 'draft_memo',
    prompt,
    sourceIsUploadedDocument: false, // In a real app, if gaps were user-supplied, this might be true, but here they are generated by our system.
    model: 'reasoning',
    systemInstruction: SYSTEM_INSTRUCTION
  });

  decisionTrail.push(
    `Outbound decision: ${result.outboundDecision.action} (rule: ${result.outboundDecision.ruleIdMatched})`
  );
  if (result.inboundDecision) {
    decisionTrail.push(
      `Inbound decision: ${result.inboundDecision.action} (rule: ${result.inboundDecision.ruleIdMatched})`
    );
  }

  if (!result.ok || !result.output) {
    return {
      ok: false,
      memo: '',
      blockedReason: result.blockedReason,
      decisionTrail
    };
  }

  // Clean up any potential markdown code block wrappers
  const cleanedMemo = result.output
    .replace(/<thinking>[\s\S]*?<\/thinking>/gi, '') // strip Gemini thinking blocks
    .replace(/^```markdown\s*/im, '')
    .replace(/^```\s*/im, '')
    .replace(/\s*```\s*$/im, '')
    .trim();

  decisionTrail.push(`Successfully drafted memo (${cleanedMemo.length} chars)`);

  return {
    ok: true,
    memo: cleanedMemo,
    decisionTrail
  };
}
